#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
# Standard wrapper launcher. If gradle-wrapper.jar is missing, run
# `gradle wrapper` once (with Gradle installed) to regenerate it, or open
# this project in Android Studio, which will regenerate the wrapper
# automatically on first sync.
##############################################################################

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
APP_HOME=$(cd "$(dirname "$0")" && pwd -P)
APP_NAME="Gradle"
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
